# Generated by Django 3.1.7 on 2021-04-12 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrow',
            fields=[
                ('brw_pk', models.AutoField(primary_key=True, serialize=False, verbose_name='Barrow ID')),
                ('brw_ttl', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Barrow Total')),
                ('brw_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Barrow Date')),
                ('brw_itm', models.ManyToManyField(to='item.Item', verbose_name='Barrow Item')),
            ],
            options={
                'verbose_name': 'Barrow',
                'verbose_name_plural': 'Barrows',
                'ordering': ['brw_dt'],
            },
        ),
    ]
